# Site settings
name: Ryan Sandan
title: Ryan Sandan
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://rsandan.github.io/
baseurl: ''
email: rsandan99@gmail.com
cover: https://rsandan.github.io/img/og.png
logo: https://rsandan.github.io/img/emojis/technologist.png
resume: https://rsandan.github.io/resume.pdf
social:
  - title: email
    url: mailto:rsandan99@gmail.com
  - title: github
    url: https://github.com/rsandan
  - title: linkedin
    url: https://www.linkedin.com/in/rsandan

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
